baseURL: "https://blog.mbrt.dev/"
title: mbrt blog
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

pagination:
  pagerSize: 5

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 10
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "mbrt personal blog"
  author: Michele Bertasi
  coverAlt: "Picture of a real world pirate."

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true

  assets:
    disableHLJS: true

  # For a simple 404
  notFound:
    title: "Page not found"
    description: "This page was not found."
    paragraph: "Nothing to see here, buddy."

  homeInfoParams:
    Title: "mbrt blog"
    Content: >
      I'm a Software Engineer. My main interests are related to Linux, Kubernetes,
      data science, C++, Rust, Go, security and reverse engineering. In Real Life
      I love spending time with my family, reading, listening to music and playing
      sports.

  socialIcons:
    - name: github
      url: "https://github.com/mbrt"
    - name: twitter
      url: "https://twitter.com/mbrt_dev"
    - name: linkedin
      url: "https://www.linkedin.com/in/michelebertasi/"
    - name: RsS
      url: "index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: false
    style: dracula

services:
  x:
    disableInlineCSS: true
