baseURL = "https://blog.mbrt.dev/"
languageCode = "en"
title = "mbrt blog"
theme = "color-your-world"

enableEmoji = true
enableInlineShortcodes = true
paginate = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    # To make use of the custom Chroma, this should be false
    # The default is true
    noClasses = false


[params]
  # Site description
  description = "mbrt personal blog"
  # Author
  author      = "Michele Bertasi"
  authorDesc  = "JASE: Just Another Software Engineer"
  # Site cover, for Open Graph, Twitter Cards and Schema.org
  # It will be used if the current page doesn't have a image cover
  # File will be picked from the "assets" directory
  # Comment the lines if you don't want to use it
  cover     = "img/me.jpg"
  coverAlt  = "Picture of a real world pirate."
  # Shows a message in the footer about JavaScript being disabled
  # The default is false
  hasNoscriptNotice = true
  # Default path for images in posts
  # ie.: "content/some-post/img"
  # Can also be set PER PAGE
  imgPath = "img"

  # Default classes for markup image 
  # Modifies the default behavior of images placed via markdown
  # Can also be set PER PAGE via front matter
  # Available classes are: border and borderless
  # There's no default value
  markupImgClass = ""
  # This will append a separator (of your choice) along the site title to your <title>
  titleSeparator = "|"

  [params.search]
    # Enable search form (at the post list)
    # The default value is false
    enable = true
    # Optional placeholder for search field
    placeholder = "ie.: lorem ipsum"

  [params.style]
    # Dark mode as default
    # User preferences (site/system settings) will still have priority over it
    # The default is false
    isDark = true
    # Disable the use of system settings (prefers-color-scheme)
    # The default is false
    ignoreSystemSettings = true
    # Accent colors for light and dark mode respectively
    lightAccent  = "#225670" # Default is "#225670"
    darkAccent   = "#db474f" # Default is "#dd587c"
    # Use an icon or text for footnote return links
    # The default is false
    hasIconAsFootnoteReturnLink = true
    # For the social shortcode
    # Use flexbox (with flex-grow) or grid (equal width)
    # The default is false
    socialIsFlex = true
    # Keep anchor links hidden until it's focused/hovered
    # The default is false
    hideAnchors = true
    # To make use of the custom Chroma, this should be true
    # and "noClasses" (at markup.highlight) should be false
    # The default is true
    useCustomChroma = true

  # For a simple 404
  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found."
    paragraph     = "Nothing to see here, buddy."

  [params.social.centralized]
    github        = ["mbrt", "mbrt"]
    linkedin      = ["michelebertasi"]
    twitter       = ["mbrt_dev", "@mbrt_dev"]

  # The "entry" here IS important. It's used to load the data.
  [params.social.decentralized]
    
    
[privacy]
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

[services]
  [services.twitter]
    disableInlineCSS = true

[languages]
  [languages.en]
    languageName = "English"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "about/"
      [[languages.en.menu.main]]
        name = "Posts"
        weight = 2
        url = "posts/"
      [[languages.en.menu.main]]
        name = "Contact"
        weight = 3
        url = "contact/"
